export const GETPOKEMONDATA = "GETPOKEMONDATA"

export const ADDTOHEART = "ADDTOHEART"

export const REMOVEFROMHEART = "REMOVEFROMHEART"

export const POKEMONDETAILS = "POKEMONDETAILS"

export const SEARCHINPUTIEMS = "SEARCHINPUTIEMS"

export const POKEMONCOMPARITION = "POKEMONCOMPARITION"

export const REMOVECOMPARESELECTION = "REMOVECOMPARESELECTION"